### ISSUE TITLE
Please use sub-module 

### ISSUE THREAD

**Issue by dcworldwide** [MeteorPackaging/Chart.js#2]
Hi @dandv, could you use a sub-module so that the project stays in sync with upstream? I can sub a PR if you point me in the right direction. I've never set one up so not sure how to go about it.

**Comment by dandv** [comment]
The project can be synced with the upstream right now:

```
git remote add upstream git@github.com:nnnick/Chart.js.git
git fetch upstream
git merge upstream/master
git push origin master
```

For the future, we're moving towards submodules indeed (see my [Webix skin](https://github.com/MeteorPackaging/webix-skin-material-design) wrappers, for example). There's a new "sister repo" approach, which @splendido might be able to help with.

**Comment by splendido** [comment]
yes, @dandv is right...
We're playing with `jsPDF` and `snap.svg` to see whether we can converge on a standard and simple approach.
Please see [jspdf-core-wrapper](https://github.com/MeteorPackaging/jspdf-core-wrapper), [jspdf-AutoTable-wrapper](https://github.com/MeteorPackaging/jspdf-AutoTable-wrapper), and [snapsvg-wrapper](https://github.com/MeteorPackaging/snapsvg-wrapper). And a bit of discussion [here](https://github.com/MeteorPackaging/discussions/issues/18) and [here](https://github.com/MeteorPackaging/discussions/issues/13)

If you like to join the party, please let me know and I'll create a brand new repo for the chart.js wrapper.

**Comment by dcworldwide** [comment]
Thanks all. I'm glad that you are tackling this issue I think it is a major meteor component in need for improvement

**Comment by macrozone** [comment]
this package hasn't been updated for some time. Could you please publish a new release to atmosphere?

**Comment by cshanejennings** [comment]
Agreed, running into an issue with the older version.  Any plans to update?

**Comment by dandv** [comment]
[Chart.js can be used from npm](https://github.com/MeteorPackaging/Chart.js/issues/6#issuecomment-220187472)
