### ISSUE TITLE
Plans to Upgrade?

### ISSUE THREAD

**Issue by zachariahtimothy** [MeteorPackaging/Chart.js#6]
I see this has not been upgraded in some time and chart js has. Is there any plans to upgrade and keep up with Chart.js or can I complete the upgrade? If not I will create my own Meteor wrapper but would rather not have so many versions on Atmosphere. Thanks!

**Comment by jmsalash** [comment]
@zachariahtimothy 
Hi,
I just created my own Meteor package for v2-beta jmsalash:chartjs, however I agree with you, better not adding unnecessary packages.
Did you create your own? Mine is having issues finding momentjs so if you have something better, happy to delete mine.
Thanks

**Comment by zachariahtimothy** [comment]
I have not had a change to focus on my apps charting, but I am using this library and it seems to work. https://github.com/mfpierre/meteor-chartist-js

**Comment by jmsalash** [comment]
Thanks,
I saw those charts too, but I liked chartjs more. My package seems to work beside a warning about momentjs, which I think still should work, so I'll stick to it until something else comes out.
Cheers

**Comment by jsbono** [comment]
I too would like to see this package updated (or a new one) to the latest chartjs as there have been a number of changes and bug fixes in the core library of chartjs

**Comment by jsandlund** [comment]
Ditto!

**Comment by dkmooers** [comment]
+1. I'm using $.getScript() with v2 served from cdnjs, but it's a bit annoying, would love to have this bundled with V2 of ChartJS!

**Comment by jmsalash** [comment]
No need for an Atmosphere package anymore. With Meteor 1.3 you can install the chart.js npm. V2 is now available for prod. too.

**Comment by dkmooers** [comment]
Ah, perfect, thanks.
