### ISSUE TITLE
IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-0.5) is negative.

### ISSUE THREAD

**Issue by phongyewtong** [MeteorPackaging/Chart.js#7]
I have this when I draw my chart. It say this is fixed in chartjs 2.0 but when is the fix coming to meteor packaging?

> IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-0.5) is negative.

**Comment by dandv** [comment]
Please [use the package via npm directly](https://github.com/MeteorPackaging/Chart.js/issues/9#issuecomment-246059893).
