### ISSUE TITLE
Meteor and Chartjs v2

### ISSUE THREAD

**Issue by Molosc** [MeteorPackaging/Chart.js#9]
Hi
Is there a package to run the v2 of Chartjs with Meteor?
To use the same syntax as in the documentation:

```
var myChart = new Chart(document.getElementById("myChart"), {
    type: 'bar',
    data: { ... },
    options: { ... },
});
```

It would be great!
Thanks

**Comment by dandv** [comment]
Have you tried using the module directly via npm imports with Meteor 1.3+?

**Comment by Molosc** [comment]
Not yet, but sure, it should be the right way now.
Thank you
